spring:
  application:
    name: aegis-support
  
  profiles:
    active: local
  
  datasource:
    url: jdbc:postgresql://localhost:5432/aegis_support
    username: aegis_user
    password: aegis_password
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        
  redis:
    host: ${SPRING_REDIS_HOST:localhost}
    port: ${SPRING_REDIS_PORT:6379}
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        
  security:
    user:
      name: admin
      password: admin123
      
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8080
  servlet:
    context-path: /api
  compression:
    enabled: true
  http2:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
        agent.latency: true

logging:
  level:
    com.aegis: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/aegis-support.log

aegis:
  security:
    api-key-header: X-API-Key
    rate-limit:
      requests-per-second: 5
      burst-capacity: 10
    pii:
      redaction-patterns:
        - "\\b\\d{13,19}\\b"  # Credit card numbers
        - "\\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Z|a-z]{2,}\\b"  # Email addresses
      replacement: "****REDACTED****"
  
  agents:
    timeout:
      tool-call: 1000  # 1 second
      flow-budget: 5000  # 5 seconds
    retry:
      max-attempts: 2
      backoff:
        initial: 150
        multiplier: 2.0
    circuit-breaker:
      failure-threshold: 3
      timeout: 30000  # 30 seconds
      
  performance:
    query-timeout: 100  # 100ms p95 target
    max-transactions-per-page: 1000
    cache-ttl: 300  # 5 minutes
